### ISSUE TITLE
After upgrading from 0.28 Net::OAuth signature fails

### ISSUE THREAD

**Issue by vti** [toddr/Crypt-OpenSSL-RSA#14]
After upgrading from 0.28 signatures calculated by Net::OAuth are not valid anymore.

**Comment by vti** [comment]
Bisecting shows this commit as the first bad one 13df4d34e7cbc9d067f863ddb94260a26df3c9e6

**Comment by vti** [comment]
Apparently this option is required:

```
$private_key->use_sha1_hash;
```

Maybe this can be documented.

**Comment by jwittkoski** [comment]
This bit me as well - changing the default signing behavior to sha256 instead of the prior sha1 should have been listed as a backwards incompatible change.

**Comment by toddr** [comment]
This has been fixed in 247d91bf3278173b0cf4a96255a14bbbc7304074 and has been released to CPAN as 0.31
