### ISSUE TITLE
Documentation incorrect/inconsistent

### ISSUE THREAD

**Issue by rskaarup** [toddr/Crypt-OpenSSL-RSA#23]
Here:

https://metacpan.org/pod/Crypt::OpenSSL::RSA

it says "use_sha256_hash is the default hash mode when available" - which is not correct.

Here:

https://github.com/toddr/Crypt-OpenSSL-RSA

it says "use_sha1_hash is the default". 

Please correct it on cpan, so others don't waste time thinking "use_sha256_hash()" is unnecessary. :-)

Thanks for the great module!

**Comment by toddr** [comment]
README.md now matches the more up to date POD on CPAN.
