### ISSUE TITLE
Get rurban to re-submit his changes 

### ISSUE THREAD

**Issue by toddr** [toddr/Crypt-OpenSSL-RSA#8]
@rurban, would you mind splitting up https://github.com/monken/Crypt-OpenSSL-RSA/pull/3? and re-submitting here as different pull requests? master has changed enough that merging it is impractical at this point.

**Comment by rurban** [comment]
Moritz Onken is the maintainer. If you or him cannot handle it, let someone else handle it.

**Comment by toddr** [comment]
Actually I’m doing the next release
